// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package postgres

import (
	"github.com/google/uuid"
)

type Resource struct {
	ID            int32
	OriginalUrl   string
	ShortUrl      string
	CorrelationID uuid.UUID
}
