// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package postgres

import (
	"context"
)

const createResource = `-- name: CreateResource :one
INSERT INTO resource (original_url, shortened_url)
VALUES ($1, $2)
RETURNING id, original_url, shortened_url
`

type CreateResourceParams struct {
	OriginalUrl  string
	ShortenedUrl string
}

func (q *Queries) CreateResource(ctx context.Context, arg CreateResourceParams) (Resource, error) {
	row := q.db.QueryRow(ctx, createResource, arg.OriginalUrl, arg.ShortenedUrl)
	var i Resource
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortenedUrl)
	return i, err
}

const getResourceByID = `-- name: GetResourceByID :one
SELECT id, original_url, shortened_url
FROM resource
WHERE id = $1
`

func (q *Queries) GetResourceByID(ctx context.Context, id int32) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByID, id)
	var i Resource
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortenedUrl)
	return i, err
}

const getResourceByURL = `-- name: GetResourceByURL :one
SELECT id, original_url, shortened_url
FROM resource
WHERE shortened_url = $1
`

func (q *Queries) GetResourceByURL(ctx context.Context, shortenedUrl string) (Resource, error) {
	row := q.db.QueryRow(ctx, getResourceByURL, shortenedUrl)
	var i Resource
	err := row.Scan(&i.ID, &i.OriginalUrl, &i.ShortenedUrl)
	return i, err
}
